### ISSUE TITLE
Cannot Import namecom

### ISSUE THREAD

**Issue by arjun8822** [CtheSky/namecom#1]
I installed pynamecom using pip and when I am trying to import it, I am getting ModuleNotFoundError. 

![Screenshot 2019-09-17 at 12 22 29 PM](https://user-images.githubusercontent.com/20962287/65018062-d6217b00-d945-11e9-9f9d-b6a7c56fedaa.png)

**Comment by CtheSky** [comment]
I have fixed it and released 0.1.4, plz try the new version.

**Comment by arjun8822** [comment]
tried.. getting same error.

**Comment by CtheSky** [comment]
Have you tired reinstall the package, I have tested it and attached a screenshot:
[![asciicast](https://asciinema.org/a/WMi9oLMQwoIO5AMfA008U0sEu.svg)](https://asciinema.org/a/WMi9oLMQwoIO5AMfA008U0sEu)

**Comment by arjun8822** [comment]
yes.. it worked after reinstalling.. Thanks
